# Generated by Django 5.0.7 on 2024-08-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lofi.dialogue')),
            ],
        ),
        migrations.CreateModel(
            name='MixAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/lofi')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lofi.mix')),
            ],
        ),
        migrations.CreateModel(
            name='MixRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/lofi')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lofi.mix')),
            ],
        ),
        migrations.AddField(
            model_name='dialogue',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lofi.mixroom'),
        ),
    ]
