# Generated by Django 5.0.7 on 2024-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofi', '0002_character_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/lofi/character'),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/lofi/character'),
        ),
    ]
