# Generated by Django 5.0.7 on 2024-07-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('translation', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/StoriesElement/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/StoriesElement/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_elements', to='dialog.chapter')),
            ],
        ),
    ]
