# Generated by Django 5.0.7 on 2024-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0002_storieselement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogueelement',
            name='type_element',
            field=models.CharField(choices=[('stories', 'Stories'), ('dialogue', 'Dialogue')], default='option1', max_length=8),
        ),
        migrations.DeleteModel(
            name='StoriesElement',
        ),
    ]
