# Generated by Django 5.0.7 on 2024-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0003_dialogueelement_type_element_delete_storieselement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogueelement',
            name='type_element',
            field=models.CharField(choices=[('stories', 'Stories'), ('dialogue', 'Dialogue')], default='stories', max_length=8),
        ),
    ]
