# Generated by Django 5.0.7 on 2024-08-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0004_alter_dialogueelement_type_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('variant_1', models.CharField(max_length=100)),
                ('variant_2', models.CharField(max_length=100)),
                ('variant_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dialogueelement',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialog.test'),
        ),
    ]
