# Generated by Django 5.0.7 on 2024-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0005_test_dialogueelement_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='antwort',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
