# Generated by Django 5.0.7 on 2024-08-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0006_test_antwort'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='gram_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/chapter/'),
        ),
    ]
