# Generated by Django 5.0.7 on 2024-08-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0009_alter_modul_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialog.chapter'),
        ),
    ]
