# Generated by Django 5.0.7 on 2024-08-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_sentence', models.TextField()),
                ('translation', models.TextField()),
            ],
        ),
    ]
