# Generated by Django 5.0.7 on 2024-08-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_playlist_sentence_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/game/sentence'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/game/sentence'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/game/word')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/game/word')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='sentences.playlist')),
            ],
        ),
    ]
